export type ToolCategory = 'Growth' | 'Content' | 'Marketing' | 'Analytics';

export interface InstagramTool {
  slug: string;
  title: string;
  description: string;
  category: ToolCategory;
  badges?: string[];
  seoKeywords?: string[];
  seoTitle?: string;
  seoDescription?: string;
}

export const toolCategoryTabs = ['All', 'Growth', 'Content', 'Marketing', 'Analytics'] as const;
export type ToolCategoryTab = typeof toolCategoryTabs[number];

export const instagramTools: InstagramTool[] = [
  {
    slug: 'ai-brand-influencer-matcher',
    title: 'AI Brand–Influencer Matcher',
    description: 'Get matched with brand partnership opportunities based on your profile and audience.',
    category: 'Marketing',
    badges: ['Free'],
    seoKeywords: ['brand influencer matcher', 'instagram brand deals', 'influencer partnerships', 'brand collaboration finder', 'instagram sponsorship'],
    seoTitle: 'Free AI Brand-Influencer Matcher | Find Instagram Brand Partnerships',
    seoDescription: 'Connect with brands for Instagram partnerships using AI. Find sponsorships, product gifting, and collaboration opportunities. Free brand matching tool.',
  },
  {
    slug: 'ai-product-matchmaker',
    title: 'AI Matchmaker for Free Products',
    description: 'Discover product gifting collaborations tailored to your niche and content style.',
    category: 'Marketing',
    badges: ['Free'],
    seoKeywords: ['free products for influencers', 'brand collaboration', 'influencer gifting', 'free product partnerships', 'pr packages'],
    seoTitle: 'AI Matchmaker for Free Products | Find Brand Gifting Opportunities',
    seoDescription: 'Get matched with brands offering free products and gifting. AI-powered tool for influencer collaborations and PR packages.',
  },
  {
    slug: 'instagram-ads-spy',
    title: 'Instagram Ads Spy Tool',
    description: 'Analyze ads from competitors and brands to inspire creatives and strategy.',
    category: 'Marketing',
    badges: ['Free'],
    seoKeywords: ['instagram ads spy', 'competitor ads analysis', 'instagram advertising', 'ad spy tool', 'instagram ad library'],
    seoTitle: 'Free Instagram Ads Spy Tool | Analyze Competitor Ad Campaigns',
    seoDescription: 'Spy on competitor Instagram ads and discover successful ad strategies. Free tool to analyze creatives and campaigns.',
  },
  {
    slug: 'fake-follower-checker',
    title: 'Instagram Fake Follower Checker',
    description: 'Estimate follower quality and spot potential bots or suspicious patterns.',
    category: 'Analytics',
    badges: ['Free'],
    seoKeywords: ['fake follower checker', 'instagram fake followers', 'bot checker instagram', 'follower quality checker', 'instagram audit'],
    seoTitle: 'Free Instagram Fake Follower Checker | Detect Bots & Fake Followers',
    seoDescription: 'Check for fake followers and bots on Instagram. Free audit tool to ensure authentic engagement and detect suspicious patterns.',
  },
  {
    slug: 'caption-generator',
    title: 'Instagram Caption Generator',
    description: 'Generate captions optimized for engagement and your brand voice.',
    category: 'Content',
    badges: ['AI', 'Free'],
    seoKeywords: ['instagram caption generator', 'ai caption generator', 'instagram captions', 'caption ideas', 'social media captions'],
    seoTitle: 'Free AI Instagram Caption Generator | Create Engaging Captions',
    seoDescription: 'Generate engaging Instagram captions with AI. Create perfect captions for posts and Reels that boost engagement.',
  },
  {
    slug: 'content-ideas-generator',
    title: 'Instagram Content Ideas Generator',
    description: 'Get fresh content ideas for posts, stories, and Reels based on your niche.',
    category: 'Content',
    badges: ['AI', 'Free'],
    seoKeywords: ['instagram content ideas', 'content ideas generator', 'instagram post ideas', 'instagram reels ideas', 'viral content ideas'],
    seoTitle: 'Free Instagram Content Ideas Generator | Get Fresh Post & Reels Ideas',
    seoDescription: 'Generate unlimited Instagram content ideas for posts, stories, and Reels. Never run out of creative ideas with our AI tool.',
  },
  {
    slug: 'reel-downloader',
    title: 'Instagram Reel Downloader',
    description: 'Download Instagram reels in high quality. Fast, secure, and free. No watermarks or login required.',
    category: 'Content',
    badges: ['Free'],
    seoKeywords: ['instagram reel downloader', 'download instagram reels', 'instagram video downloader', 'save instagram reels', 'free reel downloader', 'reel saver'],
    seoTitle: 'Free Instagram Reel Downloader | Download Reels in HD',
    seoDescription: 'Download Instagram reels in high quality for free. Fast, secure, and easy to use. No watermarks, no login required.',
  },
  {
    slug: 'emv-calculator',
    title: 'Instagram Earned Media Value (EMV) Calculator',
    description: 'Estimate the earned media value for creators or campaigns.',
    category: 'Analytics',
    badges: ['Free'],
    seoKeywords: ['earned media value calculator', 'emv calculator', 'instagram emv', 'influencer worth calculator', 'instagram roi calculator'],
    seoTitle: 'Free Instagram EMV Calculator | Calculate Earned Media Value',
    seoDescription: 'Calculate Instagram Earned Media Value (EMV) instantly. Estimate content worth and ROI for influencer campaigns.',
  },
  {
    slug: 'engagement-calculator',
    title: 'Instagram Engagement Calculator',
    description: 'Calculate engagement rate using likes, comments, and followers.',
    category: 'Analytics',
    badges: ['Free'],
    seoKeywords: ['engagement calculator', 'instagram engagement calculator', 'calculate engagement rate', 'instagram metrics calculator', 'engagement rate formula'],
    seoTitle: 'Free Instagram Engagement Calculator | Calculate Engagement Rate',
    seoDescription: 'Calculate Instagram engagement rate with likes, comments, and followers. Get accurate engagement metrics instantly.',
  },
  {
    slug: 'engagement-rate-calculator',
    title: 'Instagram Engagement Rate Calculator (Posts/Reels)',
    description: 'Check engagement rates and performance signals for posts and Reels.',
    category: 'Analytics',
    badges: ['Free'],
    seoKeywords: ['instagram engagement rate calculator', 'engagement rate calculator', 'instagram analytics', 'instagram reels engagement', 'calculate engagement rate'],
    seoTitle: 'Free Instagram Engagement Rate Calculator | Posts & Reels Analytics',
    seoDescription: 'Calculate Instagram engagement rate for posts and Reels. Optimize your content strategy with accurate analytics.',
  },
  {
    slug: 'follower-tracker',
    title: 'Instagram Follower Count Tracker (Real-Time)',
    description: 'Track follower changes over time to monitor growth and churn.',
    category: 'Growth',
    badges: ['Free'],
    seoKeywords: ['instagram follower tracker', 'follower count tracker', 'real time follower count', 'instagram growth tracker', 'track instagram followers'],
    seoTitle: 'Free Instagram Follower Tracker | Real-Time Follower Count',
    seoDescription: 'Track Instagram follower growth in real-time. Monitor follower changes and analyze growth trends with our free tool.',
  },
  {
    slug: 'ratio-calculator',
    title: 'Follower-to-Following Ratio Calculator',
    description: 'Understand account health with follower/following ratio insights.',
    category: 'Analytics',
    badges: ['Free'],
    seoKeywords: ['follower to following ratio', 'instagram ratio calculator', 'follower following calculator', 'instagram account health', 'optimal follower ratio'],
    seoTitle: 'Free Follower-to-Following Ratio Calculator | Instagram Health Check',
    seoDescription: 'Calculate Instagram follower-to-following ratio. Check account health and maintain optimal balance with our free calculator.',
  },
  {
    slug: 'fancy-fonts-generator',
    title: 'Instagram Fancy Fonts Generator',
    description: 'Generate copy‑paste fancy fonts for your bio and captions.',
    category: 'Content',
    badges: ['Free'],
    seoKeywords: ['fancy fonts generator', 'instagram fonts', 'cool fonts for instagram', 'instagram bio fonts', 'stylish fonts instagram'],
    seoTitle: 'Free Instagram Fancy Fonts Generator | Cool Fonts for Bio & Captions',
    seoDescription: 'Generate fancy fonts for Instagram bio and captions. Copy and paste stylish text and cool fonts. Free font generator.',
  },
  {
    slug: 'ai-hashtag-generator',
    title: 'AI Hashtag Generator',
    description: 'Generate relevant hashtags for posts and Reels based on topic and category.',
    category: 'Content',
    badges: ['AI', 'Free'],
    seoKeywords: ['instagram hashtag generator', 'ai hashtag generator', 'instagram hashtags', 'trending hashtags', 'hashtag generator free'],
    seoTitle: 'Free AI Instagram Hashtag Generator | Find Best Hashtags',
    seoDescription: 'Generate viral Instagram hashtags instantly with AI. Find trending hashtags for posts and Reels to boost engagement.',
  },
  {
    slug: 'trending-hashtags-country',
    title: 'Trending Instagram Hashtags by Country',
    description: 'Find popular hashtags by location to improve discovery.',
    category: 'Growth',
    badges: ['Free'],
    seoKeywords: ['trending hashtags', 'instagram trending hashtags', 'popular hashtags by country', 'viral hashtags instagram', 'trending tags instagram'],
    seoTitle: 'Trending Instagram Hashtags by Country | Find Popular Hashtags',
    seoDescription: 'Discover trending Instagram hashtags by country and location. Find popular hashtags to boost reach and engagement.',
  },
  {
    slug: 'anonymous-highlight-viewer',
    title: 'Anonymous Instagram Highlight Viewer',
    description: 'View public highlights anonymously (privacy-first viewing).',
    category: 'Growth',
    badges: ['Free'],
    seoKeywords: ['anonymous instagram viewer', 'instagram highlights viewer', 'view instagram highlights', 'instagram story viewer anonymous', 'view instagram anonymously'],
    seoTitle: 'Anonymous Instagram Highlight Viewer | View Highlights Privately',
    seoDescription: 'View Instagram highlights anonymously without being detected. Free privacy-first tool to watch public highlights.',
  },
  {
    slug: 'influencer-comparison',
    title: 'Influencer Comparison Tool',
    description: 'Compare influencers side-by-side using key performance signals.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['influencer comparison tool', 'compare influencers', 'instagram influencer comparison', 'compare instagram accounts', 'influencer analytics comparison'],
    seoTitle: 'Free Influencer Comparison Tool | Compare Instagram Influencers',
    seoDescription: 'Compare Instagram influencers side-by-side. Analyze performance metrics and engagement rates for better partnerships.',
  },
  {
    slug: 'influencer-pricing-calculator',
    title: 'Influencer Pricing Calculator',
    description: 'Estimate pricing for sponsored posts based on account size and engagement.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['influencer pricing calculator', 'instagram post pricing', 'sponsored post pricing', 'influencer rate calculator', 'instagram collaboration pricing'],
    seoTitle: 'Free Influencer Pricing Calculator | Calculate Sponsorship Rates',
    seoDescription: 'Calculate Instagram influencer pricing for sponsored posts. Estimate fair rates based on followers and engagement.',
  },
  {
    slug: 'influencer-search',
    title: 'Influencer Search Tool',
    description: 'Discover influencers by niche, audience size, and keywords.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['influencer search tool', 'find influencers', 'instagram influencer finder', 'discover influencers', 'influencer database'],
    seoTitle: 'Free Influencer Search Tool | Find Instagram Influencers by Niche',
    seoDescription: 'Search and discover Instagram influencers by niche, audience size, and keywords. Free influencer finder tool.',
  },
  {
    slug: 'likes-followers-ratio',
    title: 'Likes-to-Followers Ratio Calculator',
    description: 'Measure engagement quality relative to follower count.',
    category: 'Analytics',
    badges: ['Free'],
    seoKeywords: ['likes to followers ratio', 'instagram ratio calculator', 'engagement ratio calculator', 'likes followers ratio calculator', 'instagram engagement ratio'],
    seoTitle: 'Free Likes-to-Followers Ratio Calculator | Measure Instagram Engagement',
    seoDescription: 'Calculate Instagram likes-to-followers ratio. Measure engagement quality and compare with industry benchmarks.',
  },
  {
    slug: 'lookalike-finder',
    title: 'Instagram Lookalike Finder',
    description: 'Find creators similar to your top performers for scaling partnerships.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['instagram lookalike finder', 'find similar influencers', 'lookalike influencers', 'similar account finder', 'find similar creators'],
    seoTitle: 'Instagram Lookalike Finder | Find Similar Influencers & Creators',
    seoDescription: 'Find Instagram influencers similar to your top performers. Discover lookalike creators to scale partnerships.',
  },
  {
    slug: 'metrics-quiz',
    title: 'Instagram Metrics Knowledge Quiz',
    description: 'Test your understanding of Instagram metrics and best practices.',
    category: 'Growth',
    badges: ['Free'],
    seoKeywords: ['instagram metrics quiz', 'instagram knowledge test', 'social media metrics quiz', 'instagram analytics quiz', 'instagram best practices'],
    seoTitle: 'Instagram Metrics Knowledge Quiz | Test Your Instagram Skills',
    seoDescription: 'Test your Instagram metrics knowledge. Learn best practices and strategies to improve Instagram performance.',
  },
  {
    slug: 'instagram-money-calculator',
    title: 'Instagram Money Calculator',
    description: 'Estimate potential earnings from sponsored content based on performance.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['instagram money calculator', 'instagram earnings calculator', 'how much money instagram', 'influencer income calculator', 'instagram sponsorship calculator'],
    seoTitle: 'Free Instagram Money Calculator | Calculate Potential Earnings',
    seoDescription: 'Calculate how much money you can make on Instagram. Estimate earnings from sponsored posts and brand deals.',
  },
  {
    slug: 'instagram-photo-downloader',
    title: 'Instagram Photo Downloader',
    description: 'Save photos from public posts and carousels (where permitted).',
    category: 'Content',
    badges: ['Free'],
    seoKeywords: ['instagram photo downloader', 'download instagram photos', 'instagram image downloader', 'save instagram photos', 'instagram downloader'],
    seoTitle: 'Free Instagram Photo Downloader | Download Instagram Images',
    seoDescription: 'Download Instagram photos from public posts and carousels. Fast, free, and easy-to-use photo downloader tool.',
  },
  {
    slug: 'instagram-reels-downloader',
    title: 'Instagram Reels Downloader',
    description: 'Download Reels from public profiles (where permitted).',
    category: 'Content',
    badges: ['Free'],
    seoKeywords: ['instagram reels downloader', 'download instagram reels', 'reels downloader', 'save instagram reels', 'instagram video downloader'],
    seoTitle: 'Free Instagram Reels Downloader | Download Reels Videos',
    seoDescription: 'Download Instagram Reels videos from public profiles. Free and easy-to-use Reels downloader in high quality.',
  },
  {
    slug: 'anonymous-story-viewer',
    title: 'Anonymous Instagram Story Viewer',
    description: 'View public stories anonymously (privacy-first viewing).',
    category: 'Growth',
    badges: ['Free'],
    seoKeywords: ['anonymous story viewer', 'instagram story viewer', 'view instagram stories anonymously', 'ig story viewer', 'instagram anonymous viewer'],
    seoTitle: 'Anonymous Instagram Story Viewer | Watch Stories Privately',
    seoDescription: 'View Instagram stories anonymously without being seen. Free tool to watch public stories privately without leaving a trace.',
  },
  {
    slug: 'username-checker',
    title: 'Instagram Username Checker',
    description: 'Check username availability and brainstorm handle ideas.',
    category: 'Growth',
    badges: ['Free', 'No login required'],
    seoKeywords: ['instagram username checker', 'check username availability', 'instagram handle checker', 'username available instagram', 'instagram name checker'],
    seoTitle: 'Free Instagram Username Checker | Check Handle Availability',
    seoDescription: 'Check Instagram username availability instantly. Find if your desired handle is available and get creative username ideas.',
  },
  {
    slug: 'web-viewer',
    title: 'Web Viewer for Instagram',
    description: 'Browse public profiles and content on the web with a simple viewer.',
    category: 'Growth',
    badges: ['Free'],
    seoKeywords: ['instagram web viewer', 'view instagram on web', 'instagram profile viewer', 'instagram online viewer', 'browse instagram without app'],
    seoTitle: 'Free Instagram Web Viewer | Browse Profiles & Content Online',
    seoDescription: 'View Instagram profiles and content on the web without the app. Simple online viewer for browsing public accounts.',
  },
  {
    slug: 'local-influencer-search',
    title: 'Local Influencer Search',
    description: 'Find influencers by location for local campaigns.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['local influencer search', 'find local influencers', 'instagram influencers near me', 'local instagram influencers', 'location based influencer search'],
    seoTitle: 'Local Influencer Search Tool | Find Instagram Influencers Near You',
    seoDescription: 'Find local Instagram influencers by city or region. Discover nearby creators for local campaigns and partnerships.',
  },
  {
    slug: 'niche-influencer-search',
    title: 'Niche Influencer Search',
    description: 'Find influencers by niche keywords in bio or content.',
    category: 'Marketing',
    badges: ['AI', 'Free'],
    seoKeywords: ['niche influencer search', 'find niche influencers', 'micro influencer finder', 'niche content creators', 'targeted influencer search'],
    seoTitle: 'Niche Influencer Search | Find Micro & Niche Instagram Influencers',
    seoDescription: 'Search for niche Instagram influencers by keywords. Find targeted micro-influencers perfect for brand partnerships.',
  },
];

export function getToolBySlug(slug: string): InstagramTool | undefined {
  return instagramTools.find((t) => t.slug === slug);
}


